-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, round(avg(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS I
INNER JOIN REST_REVIEW AS R
USING(REST_ID)
GROUP BY ADDRESS
HAVING ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC;